In [1]:
import pandas as pd

In [5]:
#Procedo a cargar mi Dataset e imprimirlo.

df = pd.read_excel('/content/drive/MyDrive/Bootcamp Análisis de Datos Código Facilito/Proyecto/Data_codigo_facilito.xlsx')
df

,Interaction ID,Contact ID,Company Number,Phone Display Name,Contact Person Number,External Phone Number (Forward),Direction,Contact Type,Started At,Wait Time,...,User Name,Direct Assignment User,Team Name,User ID,Direct Assignment IDs,Team ID,Handling Ring Groups,Disconnected By Agent,Last Contact (Yes / No),Data Status (Valid / Damaged)
0,0,0,0,UNITEL,0,NaN,IN,Answered,2023-12-31 20:34:15,2.0,...,Gutierrez Garcia Brian Alejandro,NaN,NaN,0,NaN,0,transferencias_de_dinero_suc,No,Yes,Valid
1,0,0,0,Usuario_final,0,NaN,IN,Answered,2023-12-31 20:32:30,2.0,...,Vazquez Sanchez Cynthia,NaN,NaN,0,NaN,0,transferencias_de_dinero_uf,No,Yes,Valid
2,0,0,0,UNITEL,0,NaN,IN,Answered,2023-12-31 20:25:03,2.0,...,Ramirez Zempoalteca Maria Del Carmen,NaN,NaN,0,NaN,0,transferencias_de_dinero_suc,Yes,Yes,Valid
3,0,0,0,Usuario_final,0,NaN,IN,Answered,2023-12-31 20:07:43,2.0,...,Gutierrez Garcia Brian Alejandro,NaN,NaN,0,NaN,0,transferencias_de_dinero_uf,No,Yes,Valid
4,0,0,0,UNITEL,0,NaN,IN,Answered,2023-12-31 20:04:11,2.0,...,Vazquez Sanchez Cynthia,NaN,NaN,0,NaN,0,transferencias_de_dinero_suc,Yes,Yes,Valid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218063,0,0,0,UNITEL,0,NaN,IN,Answered,2023-06-01 08:47:04,2.0,...,Cortes Melgar Jorge Armando,NaN,NaN,0,NaN,0,transferencias_de_dinero_suc,Yes,Yes,Valid
218064,0,0,0,UNITEL,0,NaN,IN,Answered,2023-06-01 08:46:54,2.0,...,Oliva Lopez Ana Valeria,NaN,NaN,0,NaN,0,transferencias_de_dinero_suc,Yes,Yes,Valid
218065,0,0,0,UNITEL,0,NaN,IN,Answered,2023-06-01 08:39:44,2.0,...,ATAQUE AGUIRRE OSCAR ALEJANDRO,NaN,NaN,0,NaN,0,transferencias_de_dinero_suc,Yes,Yes,Valid
218066,0,0,0,UNITEL,0,NaN,IN,Answered,2023-06-01 08:30:32,2.0,...,ATAQUE AGUIRRE OSCAR ALEJANDRO,NaN,NaN,0,NaN,0,transferencias_de_dinero_suc,No,Yes,Valid
218067,0,0,0,UNITEL,0,NaN,IN,Answered,2023-06-01 08:28:17,2.0,...,PeÃ±aloza Velazquez Roxana,NaN,Transferencias Matutino,0,NaN,0,transferencias_de_dinero_suc,Yes,Yes,Valid

In [6]:
#El dataset se tarda al rededor de un minuto en cargar e imprimirse por pantalla, por lo que procedo a generar una pequeña muestra de los datos para comenzar a explorar el contenido de este.
df_muestra = df.head(10)
df_muestra

,Interaction ID,Contact ID,Company Number,Phone Display Name,Contact Person Number,External Phone Number (Forward),Direction,Contact Type,Started At,Wait Time,...,User Name,Direct Assignment User,Team Name,User ID,Direct Assignment IDs,Team ID,Handling Ring Groups,Disconnected By Agent,Last Contact (Yes / No),Data Status (Valid / Damaged)
0,0,0,0,UNITEL,0,NaN,IN,Answered,2023-12-31 20:34:15,2.0,...,Gutierrez Garcia Brian Alejandro,NaN,NaN,0,NaN,0,transferencias_de_dinero_suc,No,Yes,Valid
1,0,0,0,Usuario_final,0,NaN,IN,Answered,2023-12-31 20:32:30,2.0,...,Vazquez Sanchez Cynthia,NaN,NaN,0,NaN,0,transferencias_de_dinero_uf,No,Yes,Valid
2,0,0,0,UNITEL,0,NaN,IN,Answered,2023-12-31 20:25:03,2.0,...,Ramirez Zempoalteca Maria Del Carmen,NaN,NaN,0,NaN,0,transferencias_de_dinero_suc,Yes,Yes,Valid
3,0,0,0,Usuario_final,0,NaN,IN,Answered,2023-12-31 20:07:43,2.0,...,Gutierrez Garcia Brian Alejandro,NaN,NaN,0,NaN,0,transferencias_de_dinero_uf,No,Yes,Valid
4,0,0,0,UNITEL,0,NaN,IN,Answered,2023-12-31 20:04:11,2.0,...,Vazquez Sanchez Cynthia,NaN,NaN,0,NaN,0,transferencias_de_dinero_suc,Yes,Yes,Valid
5,0,0,0,Usuario_final,0,NaN,IN,Answered,2023-12-31 19:59:20,2.0,...,Ramirez Zempoalteca Maria Del Carmen,NaN,NaN,0,NaN,0,transferencias_de_dinero_uf,Yes,Yes,Valid
6,0,0,0,NaN,0,NaN,IN,Answered,2023-12-31 19:54:07,2.0,...,Murillo Esquivel Abril Sahori,NaN,NaN,0,NaN,0,presta_prenda,No,Yes,Valid
7,0,0,0,Usuario_final,0,NaN,IN,Answered,2023-12-31 19:43:22,2.0,...,Reyes Cruz Alberto,NaN,NaN,0,NaN,0,transferencias_de_dinero_uf,No,Yes,Valid
8,0,0,0,Usuario_final,0,NaN,IN,Answered,2023-12-31 19:40:01,2.0,...,Vazquez Sanchez Cynthia,NaN,NaN,0,NaN,0,transferencias_de_dinero_uf,Yes,Yes,Valid
9,0,0,0,Usuario_final,0,NaN,IN,Answered,2023-12-31 19:38:07,2.0,...,Gutierrez Garcia Brian Alejandro,NaN,NaN,0,NaN,0,transferencias_de_dinero_uf,No,Yes,Valid

In [7]:
#deseo conocer los valores numéricos del data set
estadisticos_basicos = df_muestra.describe()
estadisticos_basicos

,Interaction ID,Contact ID,Company Number,Contact Person Number,External Phone Number (Forward),Started At,Wait Time,Time to Missed,Abandon Time,Short Abandon Time,...,Soft Hold Time,Hold Time,After Call Work Time,Finished At,Duration,Handle Time,Direct Assignment User,User ID,Direct Assignment IDs,Team ID
count,10.0,10.0,10.0,10.0,0.0,10,10.0,0.0,0.0,0.0,...,0.0,0.0,5.0,10,10.000000,10.000000,0.0,10.0,0.0,10.0
mean,0.0,0.0,0.0,0.0,NaN,2023-12-31 20:03:51.900000,2.0,NaN,NaN,NaN,...,NaN,NaN,5.0,2023-12-31 20:08:09.800000,257.100000,254.300000,NaN,0.0,NaN,0.0
min,0.0,0.0,0.0,0.0,NaN,2023-12-31 19:38:07,2.0,NaN,NaN,NaN,...,NaN,NaN,5.0,2023-12-31 19:42:28,55.000000,52.000000,NaN,0.0,NaN,0.0
25%,0.0,0.0,0.0,0.0,NaN,2023-12-31 19:46:03.249999872,2.0,NaN,NaN,NaN,...,NaN,NaN,5.0,2023-12-31 19:50:24.750000128,186.250000,183.250000,NaN,0.0,NaN,0.0
50%,0.0,0.0,0.0,0.0,NaN,2023-12-31 20:01:45.500000,2.0,NaN,NaN,NaN,...,NaN,NaN,5.0,2023-12-31 20:06:00.500000,244.500000,242.000000,NaN,0.0,NaN,0.0
75%,0.0,0.0,0.0,0.0,NaN,2023-12-31 20:20:43,2.0,NaN,NaN,NaN,...,NaN,NaN,5.0,2023-12-31 20:24:47.249999872,330.750000,327.750000,NaN,0.0,NaN,0.0
max,0.0,0.0,0.0,0.0,NaN,2023-12-31 20:34:15,2.0,NaN,NaN,NaN,...,NaN,NaN,5.0,2023-12-31 20:38:11,491.000000,488.000000,NaN,0.0,NaN,0.0
std,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,...,NaN,NaN,0.0,NaN,122.213338,122.092906,NaN,0.0,NaN,0.0

In [8]:
# Entre los campos Connect Time y Talk Time me doy cuenta de que hay campos que no se visualizan. Procederé a explorarlos:
estadisticos_basicos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, count to std
Data columns (total 26 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Interaction ID                   8 non-null      float64
 1   Contact ID                       8 non-null      float64
 2   Company Number                   8 non-null      float64
 3   Contact Person Number            8 non-null      float64
 4   External Phone Number (Forward)  1 non-null      float64
 5   Started At                       7 non-null      object
 6   Wait Time                        8 non-null      float64
 7   Time to Missed                   1 non-null      float64
 8   Abandon Time                     1 non-null      float64
 9   Short Abandon Time               1 non-null      float64
 10  Time to Voicemail                1 non-null      float64
 11  Ring Time                        8 non-null      float64
 12  Connect Time                     1 non-null      float64
 13  Connected At                     1 non-null      float64
 14  Talk Time                        8 non-null      float64
 15  Hard Hold Time                   1 non-null      float64
 16  Soft Hold Time                   1 non-null      float64
 17  Hold Time                        1 non-null      float64
 18  After Call Work Time             8 non-null      float64
 19  Finished At                      7 non-null      object
 20  Duration                         8 non-null      float64
 21  Handle Time                      8 non-null      float64
 22  Direct Assignment User           1 non-null      float64
 23  User ID                          8 non-null      float64
 24  Direct Assignment IDs            1 non-null      float64
 25  Team ID                          8 non-null      float64
dtypes: float64(24), object(2)
memory usage: 1.7+ KB

In [9]:
#ya identificado el campo, veré cual es su información:
df['Connected At']

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
218063   NaN
218064   NaN
218065   NaN
218066   NaN
218067   NaN
Name: Connected At, Length: 218068, dtype: float64

In [10]:
df['Connected At'].value_counts()
#No detecto información útil para el ejercicio que llevaré acabo, por lo que terminaremos descartando la columna más adelante.

Connected At
45078.443993    1
45290.606204    1
45290.587361    1
45290.438310    1
45290.395567    1
               ..
45277.408194    1
45277.431481    1
45277.554514    1
45278.593137    1
45278.665116    1
Name: count, Length: 653, dtype: int64

In [11]:
#Deseo conocer la totalidad de los campos del data set
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 218068 entries, 0 to 218067
Data columns (total 45 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   Interaction ID                             218068 non-null  int64
 1   Contact ID                                 218068 non-null  int64
 2   Company Number                             218068 non-null  int64
 3   Phone Display Name                         199208 non-null  object
 4   Contact Person Number                      218068 non-null  int64
 5   External Phone Number (Forward)            0 non-null       float64
 6   Direction                                  218068 non-null  object
 7   Contact Type                               218068 non-null  object
 8   Started At                                 218068 non-null  datetime64[ns]
 9   Wait Time                                  217283 non-null  float64
 10  Time to Missed                             11 non-null      float64
 11  Abandon Time                               4417 non-null    float64
 12  Short Abandon Time                         1799 non-null    float64
 13  Time to Voicemail                          1 non-null       float64
 14  Ring Time                                  211656 non-null  float64
 15  Connect Time                               787 non-null     float64
 16  Answered At                                210905 non-null  object
 17  Connected At                               653 non-null     float64
 18  Talk Time                                  211877 non-null  float64
 19  Hard Hold Time                             6566 non-null    float64
 20  Soft Hold Time                             15563 non-null   float64
 21  Hold Time                                  13946 non-null   float64
 22  After Call Work Time                       114085 non-null  float64
 23  Finished At                                218068 non-null  datetime64[ns]
 24  Duration                                   218068 non-null  int64
 25  Handle Time                                211877 non-null  float64
 26  Inside Business Hours (Yes / No)           218068 non-null  object
 27  Inside Service Level (Yes /No)             218068 non-null  object
 28  Within Service Level Threshold (Yes / No)  218068 non-null  object
 29  Transfer Out (Yes/No)                      218068 non-null  object
 30  Transfer Out Type                          748 non-null     object
 31  Transfer In (Yes / No)                     218068 non-null  object
 32  Transfer In Type                           213 non-null     object
 33  Transfer In Type.1                         218068 non-null  object
 34  Ring Groups                                218068 non-null  object
 35  User Name                                  211839 non-null  object
 36  Direct Assignment User                     0 non-null       float64
 37  Team Name                                  51529 non-null   object
 38  User ID                                    218068 non-null  int64
 39  Direct Assignment IDs                      0 non-null       float64
 40  Team ID                                    218068 non-null  int64
 41  Handling Ring Groups                       210905 non-null  object
 42  Disconnected By Agent                      211318 non-null  object
 43  Last Contact (Yes / No)                    211318 non-null  object
 44  Data Status (Valid / Damaged)              218068 non-null  object
dtypes: datetime64[ns](2), float64(17), int64(7), object(19)
memory usage: 74.9+ MB

In [12]:
#Para el análisis que llevaré acabo, lo primero que necesito es la columna que me diga si fueron llamadas de entrada o de salida.
# Se detectó anteriormente la columna "Direction"
df['Direction'].value_counts()

Direction
IN     217281
OUT       787
Name: count, dtype: int64

In [13]:
# Podemos ver que recibieron 217281 llamadas de entrada y 787 de salida.

In [14]:
# Necesitaré el dato para saber si dichas llamadas fueron o no fueron contestadas. Para eso se detectó el campo "Contact Type"
df['Contact Type'].value_counts()

Contact Type
Answered           211052
Abandoned            4418
Short Abandoned      1799
Connected             653
Not Connected         134
Missed                 11
Voicemail               1
Name: count, dtype: int64

In [15]:
# Necesitaremos también datos sobre la llamada respecto al día y hora en la que esta ingresó.
# Se detectó el campo Started At
df['Started At']

0        2023-12-31 20:34:15
1        2023-12-31 20:32:30
2        2023-12-31 20:25:03
3        2023-12-31 20:07:43
4        2023-12-31 20:04:11
                 ...
218063   2023-06-01 08:47:04
218064   2023-06-01 08:46:54
218065   2023-06-01 08:39:44
218066   2023-06-01 08:30:32
218067   2023-06-01 08:28:17
Name: Started At, Length: 218068, dtype: datetime64[ns]

In [16]:
#necesitaremos también la información sobre de cuanto tiempo tuvo que esperar el cliente a ser atendido desde que su llamada ingresó al contact Center
#Se pudo detectar la columna "Wait time", que hace referencia a los segundos de espera del cliente antes de tener contacto con algún agente telefónico.
df['Wait Time']

0         2.0
1         2.0
2         2.0
3         2.0
4         2.0
         ...
218063    2.0
218064    2.0
218065    2.0
218066    2.0
218067    2.0
Name: Wait Time, Length: 218068, dtype: float64

In [17]:
#necesitaremos saber el dato de la hora y fecha de inicio de la llamada, desde que el agente telefónico recibió la llamda hasta que la finalizó.
#Para eso se detectaron las columnas Answered At y Finished At
df[['Answered At', 'Finished At']]

                Answered At         Finished At
0       2023-12-31 20:34:17 2023-12-31 20:38:11
1              45291.855937 2023-12-31 20:36:45
2       2023-12-31 20:25:06 2023-12-31 20:28:35
3       2023-12-31 20:07:46 2023-12-31 20:13:24
4       2023-12-31 20:04:14 2023-12-31 20:09:42
...                     ...                 ...
218063         45078.366053 2023-06-01 08:55:28
218064         45078.365937 2023-06-01 09:05:48
218065         45078.360961 2023-06-01 08:41:30
218066         45078.354572 2023-06-01 08:32:53
218067         45078.353009 2023-06-01 08:31:23

[218068 rows x 2 columns]

In [18]:
#Necesitaré también el motivo de la llamada, es decir, a que canal de comunicación se contactó el cliente.
# Se detectó la columna "Ring Groups"
df['Ring Groups'].value_counts()

Ring Groups
transferencias_de_dinero_suc           113509
transferencias_de_dinero_uf             81662
presta_prenda                           13455
banca empresarial                        5478
trn _transferencias                      3399
divisas                                   544
transferencias_de_dinero_uf_elektra        21
Name: count, dtype: int64

In [19]:
# Durante el ejercicio construiremos indicadores, para los cuales necesitaremos saber:
# - Qué tiempo habló el cliente con el agente telefónico.
# - Qué tiempo se mantuvo el cliente en espera durante la llamada.
# - Qué tiempo el agente demoró en finalizar su interacción en el sistema después de finalizar su llamada con el cliente.

# Se detectaron las siguiente columnas:

In [20]:
df['Talk Time'] # que hace referencia al tiempo hablado (en segundos) entre el cliente y el agente

0         228.0
1         251.0
2         203.0
3         332.0
4         328.0
          ...
218063    496.0
218064    410.0
218065     93.0
218066    129.0
218067    173.0
Name: Talk Time, Length: 218068, dtype: float64

In [21]:
df['Hold Time'] # que hace referencia al tiempo de espera que el agente telefónico solicitó(en segundos) al cliente ("un momento por favor") para verificar algún dato en sistema.

0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
          ...
218063      NaN
218064    716.0
218065      NaN
218066      NaN
218067      NaN
Name: Hold Time, Length: 218068, dtype: float64

In [22]:
df['After Call Work Time'] # Que hace referencia al tiempo (en segundos) que el agente tardó en terminar de tipificar su llamda en el CRM después de colgar al cliente.

0          5.0
1          NaN
2          5.0
3          5.0
4          NaN
          ...
218063     5.0
218064     5.0
218065    10.0
218066     9.0
218067    10.0
Name: After Call Work Time, Length: 218068, dtype: float64

In [23]:
# Al parecer ya tengo los datos que necesito para comenzar a trabajar, por lo que pasaré a armar mi DF

df_a_trabajar = df[["Direction", 'Contact Type', 'Started At', 'Wait Time', 'Answered At', 'Finished At', 'Ring Groups', 'Talk Time', 'Hold Time', 'After Call Work Time', 'User Name']]
df_a_trabajar

,Direction,Contact Type,Started At,Wait Time,Answered At,Finished At,Ring Groups,Talk Time,Hold Time,After Call Work Time,User Name
0,IN,Answered,2023-12-31 20:34:15,2.0,2023-12-31 20:34:17,2023-12-31 20:38:11,transferencias_de_dinero_suc,228.0,NaN,5.0,Gutierrez Garcia Brian Alejandro
1,IN,Answered,2023-12-31 20:32:30,2.0,45291.855937,2023-12-31 20:36:45,transferencias_de_dinero_uf,251.0,NaN,NaN,Vazquez Sanchez Cynthia
2,IN,Answered,2023-12-31 20:25:03,2.0,2023-12-31 20:25:06,2023-12-31 20:28:35,transferencias_de_dinero_suc,203.0,NaN,5.0,Ramirez Zempoalteca Maria Del Carmen
3,IN,Answered,2023-12-31 20:07:43,2.0,2023-12-31 20:07:46,2023-12-31 20:13:24,transferencias_de_dinero_uf,332.0,NaN,5.0,Gutierrez Garcia Brian Alejandro
4,IN,Answered,2023-12-31 20:04:11,2.0,2023-12-31 20:04:14,2023-12-31 20:09:42,transferencias_de_dinero_suc,328.0,NaN,NaN,Vazquez Sanchez Cynthia
...,...,...,...,...,...,...,...,...,...,...,...
218063,IN,Answered,2023-06-01 08:47:04,2.0,45078.366053,2023-06-01 08:55:28,transferencias_de_dinero_suc,496.0,NaN,5.0,Cortes Melgar Jorge Armando
218064,IN,Answered,2023-06-01 08:46:54,2.0,45078.365937,2023-06-01 09:05:48,transferencias_de_dinero_suc,410.0,716.0,5.0,Oliva Lopez Ana Valeria
218065,IN,Answered,2023-06-01 08:39:44,2.0,45078.360961,2023-06-01 08:41:30,transferencias_de_dinero_suc,93.0,NaN,10.0,ATAQUE AGUIRRE OSCAR ALEJANDRO
218066,IN,Answered,2023-06-01 08:30:32,2.0,45078.354572,2023-06-01 08:32:53,transferencias_de_dinero_suc,129.0,NaN,9.0,ATAQUE AGUIRRE OSCAR ALEJANDRO
218067,IN,Answered,2023-06-01 08:28:17,2.0,45078.353009,2023-06-01 08:31:23,transferencias_de_dinero_suc,173.0,NaN,10.0,PeÃ±aloza Velazquez Roxana

In [24]:
df_a_trabajar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 218068 entries, 0 to 218067
Data columns (total 11 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Direction             218068 non-null  object
 1   Contact Type          218068 non-null  object
 2   Started At            218068 non-null  datetime64[ns]
 3   Wait Time             217283 non-null  float64
 4   Answered At           210905 non-null  object
 5   Finished At           218068 non-null  datetime64[ns]
 6   Ring Groups           218068 non-null  object
 7   Talk Time             211877 non-null  float64
 8   Hold Time             13946 non-null   float64
 9   After Call Work Time  114085 non-null  float64
 10  User Name             211839 non-null  object
dtypes: datetime64[ns](2), float64(4), object(5)
memory usage: 18.3+ MB

In [25]:
# comenzaremos a explorar valores vacios
df_a_trabajar.isnull().sum()

Direction                    0
Contact Type                 0
Started At                   0
Wait Time                  785
Answered At               7163
Finished At                  0
Ring Groups                  0
Talk Time                 6191
Hold Time               204122
After Call Work Time    103983
User Name                 6229
dtype: int64

In [26]:
#procederé a explorar las columnas con valores vacíos:

# "Wait Time" No es relevante el dato nulo para esta variable, ya que, si recordamos, teníamos 787 llamadas de salida, las cuales no generan un "Wait Time"

# "Hold Time" tampoco es relevante, ya que, los agentes, cuando necesitan revisar algo en sistema, siguen con el cliente en línea, no piden tiempo en espera.

# "After Call Work" No es relevante. En estos casos los agentes primero terminan de tipificar su llamada en el CRM y posteriormente cuelgan la llamada con el cliente. Por lo que en esas llamadas nno se genera ACW

In [27]:
### PROCEDEREMOS A VERIFICAR LAS VARIABLES QUE SI SON RELEVANTES ###

In [28]:
# comenzaré explorando "Answered At"
# imprimiré por pantalla todos aquellos registros sin dato en la columna "Answered At". Esto lo hago con la finalidad de ver si tienen algo común los registros que no tienen dicho dato.
(df_a_trabajar[df_a_trabajar['Answered At'].isnull()])

,Direction,Contact Type,Started At,Wait Time,Answered At,Finished At,Ring Groups,Talk Time,Hold Time,After Call Work Time,User Name
19,IN,Short Abandoned,2023-12-31 19:02:34,2.0,NaN,2023-12-31 19:02:36,transferencias_de_dinero_uf,NaN,NaN,NaN,NaN
145,IN,Abandoned,2023-12-31 16:29:29,54.0,NaN,2023-12-31 16:30:24,transferencias_de_dinero_uf,NaN,NaN,NaN,NaN
168,IN,Abandoned,2023-12-31 16:11:37,150.0,NaN,2023-12-31 16:14:08,presta_prenda,NaN,NaN,NaN,NaN
697,IN,Abandoned,2023-12-30 19:19:50,61.0,NaN,2023-12-30 19:20:51,transferencias_de_dinero_uf,NaN,NaN,NaN,NaN
735,IN,Short Abandoned,2023-12-30 18:51:26,1.0,NaN,2023-12-30 18:51:27,transferencias_de_dinero_uf,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
217829,IN,Abandoned,2023-06-01 11:20:09,14.0,NaN,2023-06-01 11:20:24,trn _transferencias,NaN,NaN,NaN,NaN
217871,OUT,Connected,2023-06-01 11:01:32,NaN,NaN,2023-06-01 11:06:38,transferencias_de_dinero_suc,286.0,NaN,10.0,PASCACIO ROJAS MISAEL
217877,IN,Short Abandoned,2023-06-01 10:57:27,0.0,NaN,2023-06-01 10:57:27,transferencias_de_dinero_uf,NaN,NaN,NaN,NaN
217904,OUT,Connected,2023-06-01 10:39:12,NaN,NaN,2023-06-01 10:48:24,transferencias_de_dinero_suc,532.0,NaN,10.0,PASCACIO ROJAS MISAEL
218021,IN,Short Abandoned,2023-06-01 09:24:53,0.0,NaN,2023-06-01 09:24:53,transferencias_de_dinero_uf,NaN,NaN,NaN,NaN

In [29]:
(df_a_trabajar[df_a_trabajar['Direction'] == 'OUT'])

,Direction,Contact Type,Started At,Wait Time,Answered At,Finished At,Ring Groups,Talk Time,Hold Time,After Call Work Time,User Name
1137,OUT,Connected,2023-12-30 14:32:47,NaN,NaN,2023-12-30 14:40:03,transferencias_de_dinero_suc,426.0,NaN,NaN,Pascacio Rojas Misael
1190,OUT,Connected,2023-12-30 14:05:38,NaN,NaN,2023-12-30 14:09:55,transferencias_de_dinero_suc,246.0,NaN,NaN,Pascacio Rojas Misael
1526,OUT,Connected,2023-12-30 10:31:01,NaN,NaN,2023-12-30 10:38:03,transferencias_de_dinero_suc,412.0,NaN,NaN,Pascacio Rojas Misael
1598,OUT,Connected,2023-12-30 09:29:27,NaN,NaN,2023-12-30 09:42:13,transferencias_de_dinero_suc,756.0,NaN,NaN,Pascacio Rojas Misael
10707,OUT,Connected,2023-12-20 15:28:49,NaN,NaN,2023-12-20 15:32:06,transferencias_de_dinero_suc,186.0,NaN,NaN,Pascacio Rojas Misael
...,...,...,...,...,...,...,...,...,...,...,...
215759,OUT,Not Connected,2023-06-03 10:17:58,NaN,NaN,2023-06-03 10:18:09,transferencias_de_dinero_suc,NaN,NaN,10.0,PASCACIO ROJAS MISAEL
215777,OUT,Connected,2023-06-03 10:07:14,NaN,NaN,2023-06-03 10:10:39,transferencias_de_dinero_suc,183.0,NaN,9.0,PASCACIO ROJAS MISAEL
217743,OUT,Connected,2023-06-01 12:07:09,NaN,NaN,2023-06-01 12:11:14,transferencias_de_dinero_suc,229.0,NaN,9.0,PASCACIO ROJAS MISAEL
217871,OUT,Connected,2023-06-01 11:01:32,NaN,NaN,2023-06-01 11:06:38,transferencias_de_dinero_suc,286.0,NaN,10.0,PASCACIO ROJAS MISAEL
217904,OUT,Connected,2023-06-01 10:39:12,NaN,NaN,2023-06-01 10:48:24,transferencias_de_dinero_suc,532.0,NaN,10.0,PASCACIO ROJAS MISAEL

In [30]:
# Me pude percatar de que aquellos registros en los que la llamada fue abandonada no genera el dato de "Answered At".
# Tampoco genera el dato "Ansewred At" los registros que indican llamadas de salida (Campo "Direction" con tipificación "OUT"), sin embargo, estos si generan nombre del agente telefónico
# Procedré a verificar cuantos son.

In [31]:
(df_a_trabajar['Direction'] == 'OUT').value_counts()

Direction
False    217281
True        787
Name: count, dtype: int64

In [32]:
(df_a_trabajar['Contact Type'] == 'Abandoned').value_counts()

Contact Type
False    213650
True       4418
Name: count, dtype: int64

In [33]:
(df_a_trabajar['Contact Type'] == 'Short Abandoned').value_counts()

Contact Type
False    216269
True       1799
Name: count, dtype: int64

In [34]:
conteo_abandonos_y_out = 787+4418+1799 #sumatoria de llamadas abandonadas + llamadas abandonadas en corto + llamadas de salida
conteo_abandonos_y_out

7004

In [35]:
conteo_answered_at_null = 7163 # Total de llamadas sin un registro de Answred At (que son aquellas llamadas que no son contestadas por un agente tedlefónico).
conteo_answered_at_null

7163

In [36]:
answred_at_null_menos_abandono_menos_Out = conteo_answered_at_null-conteo_abandonos_y_out # Total de llamdas sin registro de "Answered At - Abanadonadas - abandonadas en corto - llamadas de salida."
answred_at_null_menos_abandono_menos_Out

159

In [37]:
registros_perdidos = conteo_answered_at_null/answred_at_null_menos_abandono_menos_Out/100
registros_perdidos

0.45050314465408803

In [38]:
# CONCLUSIONES SOBRE DATOS NULOS

'''
Después de haber desglosado todos aquellos datos nulos, nos quedamos con 159 registros. que representan el 0.4% de nuestros datos nulos, por lo que no es relevante para nuestro análisis.

Respecto a los campos

Talk Time y User Name con datos nulos de 6192 y 6229 respectivamente, podemos concluir que dichos datos faltantes derivan de las llamadas abandonadas, ya que estas sí generan un registro de que la llamada existió,
sin embargo, al no haberla atendido ningún agente, no se genera algún dato de Talk time (que es el tiempo que el agentye habla con el cliente durante la llamada), y tampoco se genera un nombre de agente, reiterando
que dicha llamada no fue atendida por el personal del contact center.

'''

### En este caso conservaremos los datos nulos, ya que los necesitaremos más adelante para contruir el panel de indicadores, dentro del cual se requeriere saber las llamadas abandonadas###

'\nDespués de haber desglosado todos aquellos datos nulos, nos quedamos con 159 registros. que representan el 0.4% de nuestros datos nulos, por lo que no es relevante para nuestro análisis.\n\nRespecto a los campos\n\nTalk Time y User Name con datos nulos de 6192 y 6229 respectivamente, podemos concluir que dichos datos faltantes derivan de las llamadas abandonadas, ya que estas sí generan un registro de que la llamada existió,\nsin embargo, al no haberla atendido ningún agente, no se genera algún dato de Talk time (que es el tiempo que el agentye habla con el cliente durante la llamada), y tampoco se genera un nombre de agente, reiterando\nque dicha llamada no fue atendida por el personal del contact center.\n\n'

In [39]:
#### Ya que tengo los datos con los cuales vamos a trabajar, procedé a exportar los datos para llevar a cabo el reporte con la información requerida###

data_reporte = df_a_trabajar.to_excel("data_reporte.xlsx")

In [41]:
# Para descargar el archivo

from google.colab import files
files.download("data_reporte.xlsx")